name: time_text
description: A time text widget. You can use it to show current time with a formatter.
version: 0.1.2
repository: https://github.com/MrHeer/time_text

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

topics:
  - time
  - text
  - widget
